# Site
title: Parquet
description: A system for queer 2D building, crafting, and narrative sandbox games.
author: Paige Ashlynn
url: "http://parquet.gay"

# Theme
remote_theme: pmarsceill/just-the-docs
color_scheme: parquet

# Collections
collections:
  blog:
    permalink: "/:collection/:path/"
    sort_by: date
    output: true

# Collection Integrations
just_the_docs:
  collections:
    blog:
      name: Dev Blog
      nav_exclude: false
      search_exclude: false

# Upper Right Navigation
aux_links:
  "Parquet on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
  "Parquet on Itch":
    - "//https://mxashlynn.itch.io/parquet"

# Search
heading_anchors: true
nav_sort: case_insensitive 
search_enabled: true
