# Site Details
title: Parquet
description: A system for queer 2D building, crafting, and narrative sandbox games.
author: Paige Ashlynn
email: ""
baseurl: ""
url: "http://parquet.gay"
github_username: mxashlynn

# Build settings
remote_theme: pmarsceill/just-the-docs

# Theme
color_scheme: parquet

# Upper Right Navigation
aux_links:
  "Parquet on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
  "Parquet on Itch":
    - "//https://mxashlynn.itch.io/parquet"

# Search
heading_anchors: true
nav_sort: case_insensitive 
search_enabled: true
